### PR TITLE
Update to mun_runtime to 0.3.0 + other dependencies 

### PR DESCRIPTION
**Pull request by sigmaSd**
I tested the spaceship example and it works

The pong example crashes on my machine with 
`attempted to leave type platform::platform::x11::util::input::PointerState uninitialized ` 
 It also crashes on wayland with a different error, its probably coming from ggez/winit

### CODE REVIEW

**Comment by legendiguess** [comment]
> The pong example crashes on my machine with
attempted to leave type platform::platform::x11::util::input::PointerState uninitialized
It also crashes on wayland with a different error, its probably coming from ggez/winit

Looks like this bug fixed. Can you update pong example `ggez` version and try it on your machine?

**Comment by sigmaSd** [comment]
Updating to ggez 0.6.0 cause linkage issue for alsa-sys with tetra, I'll try your suggestion once tetra updates the rodio crate version.

**Comment by sigmaSd** [comment]
Updating ggez fixed the issue I was having.

I refactored the code-base to allow multiple examples to work even if they have conflict in their dependencies tree.

**Comment by baszalmstra** [comment]
Thanks very much!

**Pull request merged**
